### ISSUE TITLE
Replace channel/grid spacing support with just frequency support

### ISSUE THREAD

**Issue by samisaab** [Telecominfraproject/oopt-tai#45] opened 2018-11-08 19:35 UTC
Remove definitions and support for channel and grid spacing control and status, and replace with definitions and support for only carrier frequency control and status.  Implementation would behave as follows.
- Software snaps to a Read/Write "Requested" frequency attribute to the highest supported grid resolution
- Software provides a Read Only "Set" frequency attribute for the resulting snapped value

**Comment by scott-emery** [comment] 2018-11-08 22:44
I like it, and I think this is where we basically converged at the workshop. Two comments:

- Would it also be worthwhile to have a read-only value for the grid resolution which was selected by the frequency?
- Also, I'd like to request, for consistency, that all frequency values be uint64's and in units of Hz. Of course the application is free to convert these values to other formats (e.g. float) and units (e.g. THz), but for all frequencies crossing the TAI interface I'd like to standardize on 64-bit Hz.

**Comment by samisaab** [comment] 2018-11-09 00:53
- Yes.  In fact, not all grid spacing is an integer multiple of another, so I was incorrect to state highest resolution.  Rather, software should determine the resolution that gets closest to the "Requested" frequency.  This also means we should keep the supported grid spacing attribute so that a user can determine what to request in some instances.
- Agreed.

**Comment by ishidawataru** [comment] 2018-11-09 04:40
@samisaab 

> This also means we should keep the supported grid spacing attribute so that a user can determine what to request in some instances.

Is the supported grid space `TAI_NETWORK_INTERFACE_ATTR_LASER_GRID_SUPPORT` enough to determine what to request?

Do we also need `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` for the calculation?

**Comment by samisaab** [comment] 2018-11-09 21:53
Yes, I think `TAI_NETWORK_INTERFACE_ATTR_LASER_GRID_SUPPORT` is enough to determine what to request.

The `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` and `TAI_NETWORK_INTERFACE_ATTR_MAX_LASER_FREQ` should remain to inform a user as well.

**Comment by samisaab** [comment] 2018-11-12 20:02
After more thought, I would still like to add `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ` and `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE` attributes, so that a user can determined how a "Requested" frequency will snap, and if they want to change channel 1 to change how it snaps.  I'm also fine with making them custom attributes if others prefer that approach instead.

**Comment by ishidawataru** [comment] 2018-11-12 23:23
Yeah, that's why I asked about `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ`.
I think you are expecting `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` to return the possible lowest frequency which the hardware supports though.

One more question I came up with is what will happen if the user specifies a way lower or higher frequency which the hardware supports.

It would be useful to have some guard for error margin.
If a user specified a value which exceeds that guard, `set_attribute()` can return an error.

**Comment by samisaab** [comment] 2018-11-13 00:35
OK, sounds good.  How about returning an error if the calculated snap creates a delta between "Requested" and "Set" that is greater than the largest supported grid spacing?

**Comment by samisaab** [comment] 2018-11-14 01:15
Following are proposed changes to tainetworkif.h
- Remove following attributes
  - `TAI_NETWORK_INTERFACE_ATTR_TX_CHANNEL`
  - `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_LAMBDA`
- Add following attributes
  - `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ`
  - `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE`
- Changed `TAI_NETWORK_INTERFACE_ATTR_TX_GRID_SPACING` to `READ_ONLY`
- Changed `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ` from THz as `tai_float_t` to Hz as `tai_uint64_t`

Following are proposed usages
- `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ` for "Requested" frequency
- `TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` for "Set" frequency
- If "Requested" `<= TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ - max supported grid spacing`, return `TAI_STATUS_FAILURE`
- If "Requested" `>= TAI_NETWORK_INTERFACE_ATTR_MAX_LASER_FREQ + max supported grid spacing`, return `TAI_STATUS_FAILURE`

**Comment by ishidawataru** [comment] 2018-11-14 01:32
`TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` is `READ_ONLY` correct?

How do we use  `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ` and `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE` ?

`TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ` is `READ_ONLY` and `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE` is the attribute for the ch1 configuration?

**Comment by scott-emery** [comment] 2018-11-14 01:36
I have the same questions as @ishidawataru. @samisaab can you provide a bit more documentation on these attributes? I think what you are proposing is much better than what we currently have, I just want to be able to fully understand it.

Also, a minor point, why use the string "CH1" in the attribute names instead of "CHANNEL" or "CHAN"? Are we expecting there will be a "CH2" in the future?

**Comment by samisaab** [comment] 2018-11-14 02:51
`TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` is `READ_ONLY`

`TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ` is `READ/WRITE` and used for reading `[0x818A] [0x818B] [0x818C] [0x818D]` and reading/writing `[0xB490] [0xB491] [0xB492]` to access and change the channel 1 frequency.  This may be needed for a user to set the base of the grid they want to snap to.  If the user wants to use NVR data instead, they can set this attribute to 0.  By default, NVR data will be used.

`TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE` is `READ_ONLY`, and is used to determine if the module supports changing the channel 1 frequency.

I chose "CH1" to reference "chan_1_freq" and "channel_1_frequency", which are referenced in the MSA and OIF documents for calculating frequency and channel number.

**Comment by ishidawataru** [comment] 2018-11-14 02:56
@samisaab I see. If the module doesn't support setting `CH1_FREQ`, the set_attribute api can simply return `TAI_STATUS_ATTR_NOT_SUPPORTED_0`  https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/taistatus.h#L249 

So we don't need `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ_ADJUSTABLE`

**Comment by samisaab** [comment] 2018-11-14 02:57
OK, makes more sense.

**Comment by ishidawataru** [comment] 2018-11-14 03:01
Instead of `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ` and `TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ`, how about 

`TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` for configuration and 
`TAI_NETWORK_INTERFACE_ATTR_CURRENT_TX_LASER_FREQ` for read-only attribute?

In this way, we can add `RX_LASER_FREQ` attributes in the future if we want.

**Comment by samisaab** [comment] 2018-11-14 03:08
Sounds good to me.

**Comment by ishidawataru** [comment] 2018-11-14 03:19
@samisaab thanks. the last item I want to discuss is error guard.

> If "Requested" <= TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ - max supported grid spacing, return TAI_STATUS_FAILURE
> If "Requested" >= TAI_NETWORK_INTERFACE_ATTR_MAX_LASER_FREQ + max supported grid spacing, return TAI_STATUS_FAILURE

We could generalize this and have an attribute which specifies how much gap we allow between the requested and actual frequency.

The default value of that attribute can be max supported grid spacing width.
What do you think?

**Comment by samisaab** [comment] 2018-11-14 03:42
That sounds good.  Any suggestions on attribute names?

**Comment by ishidawataru** [comment] 2018-11-14 22:38
Here are my ideas. None of them sound right though.

`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_ALLOWED_TX_LASER_FREQ_ERROR`
`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_ALLOWED_TX_LASER_FREQ_SNAP_GAP`
`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_TX_LASER_FREQ_SNAP_GAP`
`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_TX_LASER_FREQ_ERROR`
`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_FREQ_SNAP_GAP`
`TAI_NETWORK_ATTRIBUTE_ATTR_MAX_FREQ_ERROR`

**Comment by samisaab** [comment] 2018-11-15 01:16
How about
`TAI_NETWORK_INTERFACE_ATTR_MAX_OVERSHOOT_TX_LASER_FREQ`

Also, instead of comparing to the min frequency, one should compare to the channel 1 frequency.

**Comment by samisaab** [comment] 2018-11-16 01:07
Wataru explained to me that he requested a max snap delta for every frequency set, not an overshoot at the minimum and maximum allowable frequencies.  However this get complicated because such a delta should be a function of the signal and neighboring signal bandwidths, which may not be known at this level.  We decided to omit this enhancement for now.

**Comment by samisaab** [comment] 2018-11-16 02:21
Latest changes to tainetworkif.h are as follows.

- Removed following attributes
  - `TAI_NETWORK_INTERFACE_ATTR_TX_CHANNEL`
  - `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ`
  - `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_LAMBDA`
- Added following attributes
  - `TAI_NETWORK_INTERFACE_ATTR_CURRENT_TX_LASER_FREQ`
  - `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ`
- Changed `TAI_NETWORK_INTERFACE_ATTR_TX_GRID_SPACING` to `READ_ONLY`
- Changed `TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` to `READ/WRITE`

Usage is as follow.

- `TAI_NETWORK_INTERFACE_ATTR_TX_LASER_FREQ` for "Requested" frequency
- `TAI_NETWORK_INTERFACE_ATTR_CURRENT_TX_LASER_FREQ` for "Set" frequency

However, to maintain backward compatibility, we propose to keep removed attributes as placeholders and label them "deprecated".  I have the following questions on that topic.
- How should I label a deprecated attribute?  I am currently adding the following after the `@type` line.
  - `@deprecated`
- Do I need to deprecate the following attributes, or can they just be deleted?
  - `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ`
  - `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_LAMBDA`

**Comment by scott-emery** [comment] 2018-11-17 00:40
At this point in the TAI development, the API is fairly fluid. We continue to make important modifications to converge on the best API possible. And so, I would say that there is no need to deprecate attributes. I think it will just create confusion by carrying these unused API attributes. At some point, I expect things will settle down and we will need to be more mindful of modifying existing API attributes.

I would prefer that we simply remove the following attributes:
- `TAI_NETWORK_INTERFACE_ATTR_TX_CHANNEL`
- `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_FREQ`
- `TAI_NETWORK_INTERFACE_ATTR_CHANNEL_LAMBDA`

I believe the `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ`is actually an enhancement of the `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` attribute. The `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` attribute was intended to report the `[0x818A] [0x818B] [0x818C] [0x818D]` MSA register values. What's new is that this attribute can now be written, which will alter the channel 1 (base) frequency. We should either modify the definition of `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` to be read/write or entirely replace it with `TAI_NETWORK_INTERFACE_ATTR_CH1_FREQ`. I would prefer the former, but don't feel too strongly about it.

**Comment by samisaab** [comment] 2018-11-17 04:19
OK, I will remove `TAI_NETWORK_INTERFACE_ATTR_TX_CHANNEL`

Regarding `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ `, I use it to report the result from the MSA defined register 0x8014, and I use `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` to report the result from the MSA defined register 0x8012.  These are the guaranteed minimum and maximum frequencies that the laser supports.  We could use `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` for the base frequency instead, but then the user would not know how low they could set it.

Based on this information, we could change nomenclature to differentiate the meanings more.  For instance, the MSA registers 0x8014 and 0x8012 report the results in wavelength rather than frequency, but that may make it more confusing compared to keeping everything in Hz.

**Comment by scott-emery** [comment] 2018-11-19 19:35
Ok, got it. Let's leave `TAI_NETWORK_INTERFACE_ATTR_MIN_LASER_FREQ` and `TAI_NETWORK_INTERFACE_ATTR_MAX_LASER_FREQ` as they are: read only minimum and maximum laser frequencies (in Hz) supported by the laser. The intention is to have them based upon the 0x8012 and 0x8014 MSA registers (converting wavelength to frequency).

**Comment by ishidawataru** [comment] 2019-01-25 00:07
fixed by https://github.com/Telecominfraproject/oopt-tai/pull/51/files
thank you @samisaab and @scott-emery !

**Closed as completed by ishidawataru** 2019-01-25 00:07 UTC
Labels: enhancement
